global_frame: map
rolling_window: false
track_unknown_space: true

update_frequency: 5.0
publish_frequency: 5.0

inflation:
    inflation_radius: 0.5

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}

