plugin_blacklist:
- actuator_control
- adsb
- safety_area
- 3dr_radio
- cam_imu_sync
- distance_sensor
# - fake_gps
- hil
- landing_target
- mocap_pose_estimate
- mount_control
- obstacle_distance
# - rc_io
- vfr_hud
- waypoint
- wind_estimation
- px4flow
- companion_process_status
- debug_value
- wheel_odometry
- odometry
- vibration
- odom
- setpoint_position
- setpoint_accel
- setpoint_velocity
- altitude
- esc_status
- ftp
- log_transfer
- onboard_computer_status
- manual_control
- rangefinder
- setpoint_trajectory
- trajectory
plugin_whitelist: []
#- 'sys_*'