plugin_blacklist:
- actuator_control
- adsb
- safety_area
- 3dr_radio
- cam_imu_sync
- distance_sensor
- fake_gps
- hil
- landing_target
- mocap_pose_estimate
- mount_control
- obstacle_distance
- vfr_hud
- waypoint
- wind_estimation
- px4flow
- companion_process_status
- debug_value
- wheel_odometry
- odometry
- vibration
- odom
- setpoint_position
- setpoint_accel
- setpoint_velocity
- esc_status
- ftp
- log_transfer
- onboard_computer_status
- manual_control
- rangefinder
- setpoint_trajectory
- trajectory
- play_tune
- sys_time
plugin_whitelist: # 如果模块即被同时声明在plugin_blacklist和plugin_whitelist中，也会启动
- sys_status
- vision_speed_estimate
- vision_pose_estimate
- rc_io
- altitude
- command
- global_position
- gps_rtk
- gps_status
- home_position
- imu
- local_position
- param
- setpoint_attitude
- setpoint_raw
- manual_control